---
# Tasks to install and configure PHP

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install Nginx
  apt:
    name: nginx
    state: latest
  notify: restart nginx   # Notify the handler at the task level
  become: true

- name: Ensure Apache/PHP service is running
  service:
    name: "{{ php_service }}"
    state: started
    enabled: true
  become: true

